config:
  random_seed: 109602
  max_length: 1024
  tokenizer_type: microsoft/biogpt
  eval_batch_size: 64

student_models:
  model_type_or_dir: microsoft/biogpt
  num_labels: 3
  ckpt_paths:
    - student_models/pubmedqa_biogpt/ka/teacher_DEFGM/model.epoch0.val_acc=0.7360.pt



teacher_models:
  model_type_or_dir: microsoft/biogpt
  num_labels: 3
  ckpt_paths:
    - ../../teacher_models/biogpt_pubmedqa/A/model.epoch17.ckpt 

    



data:
  type: PubMedQA
  topics: 
    - all
  test_files:
    - /home/datasets/PubMedQA/pqal_test.jsonl

